GroupProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bots import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name = 'index'),
    url(r'^bots/', include('bots.urls')),
]

bots/urls.py
from django.conf.urls import url, include
from django.views.decorators.csrf import csrf_exempt
from bots import views

app_name= 'bots'

urlpatterns = [
    url(r'^profile/(?P<profile_name>[\w\-]+)/$', views.show_profile, name ='show_profile'),
    url(r'^upgrade/$', views.upgrade, name='upgrade'),
    url(r'^leaderboards/$', views.leaderboards, name='leaderboards'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^about/$', views.about, name='about'),
    url(r'^get_bot/$', views.display_bot, name='display_bot'),
    url(r'^matchmake/$', views.validate, name = 'validate'),
    url(r'^initialize/$',views.initialize, name = 'initialize'),
    url('^update_team/$',views.resetTeam, name = 'resetTeam'),
    url(r'^create_bot/$',csrf_exempt(views.create_bot), name = 'create_bot'),
    url(r'^validate_new_bot/$',views.validate_name,name = 'validate_name'),
    url(r'^fight/$',views.fight,name = 'fight'),
]

bots/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #currency of game
    scrap = models.IntegerField(default = 100)
    # tracks who the player is interested in, assymetrical since if you follow someone that doesn't mean they follow you
    follows = models.ManyToManyField("self", symmetrical = False)
    looking_for_match = models.BooleanField(default = False)
    # robot is in quotation marks because the class hasnt been defined yet
    # also, originally implemented with blank = True, but that doesn't seem to do what I think it did, so instead I used null = True and default = None
        # robot chosen for battle
    chosen_robot= models.OneToOneField("Robot", null= True, default = None)
    wins = models.IntegerField(default = 0)
    losses = models.IntegerField(default = 0)
    def __str__(self):
        return self.user.username

class Robot(models.Model):
    owner = models.ForeignKey(Player, on_delete = models.CASCADE)
    name = models.CharField(max_length = 20, unique = True)
    value = models.IntegerField() # scrap value of robot
    type = models.CharField(max_length = 10) # class of robot
    wins = models.IntegerField(default = 0)
    losses= models.IntegerField(default = 0)
    # robot stats
    speed = models.IntegerField(null = True, blank = True)
    dodge = models.IntegerField(null = True, blank = True)
    armour = models.IntegerField(null = True, blank = True)
    weapon = models.IntegerField(null = True, blank = True)
    accuracy = models.IntegerField(null = True, blank = True)
    # returns dictionary with names of stats mapped to corresponding values
    def get_stats(self):
        stats = {
            'speed' : self.speed,
            'dodge': self.dodge,
            'armour' : self.armour,
            'weapon' : self.weapon,
            'accuracy' : self.accuracy,
        }
        return stats

    def __str__(self):
        return self.name

class Battle(models.Model):
    participants = models.ManyToManyField(Player)
    log = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        result = ""
        for p in self.participants.all():
            if result == "":
                result  = str(p)
            else:
                result += ' vs ' + str(p)
        #end for
        date = self.date.strftime('%d/%m %H:%M')
        result += ', ' + date
        #result += ', ' + str(self.date)
        if self.log:
            result += ', ' + self.log.split('\n')[-1]
        else:
            result += ', pending'

        return result

class Team(models.Model):
    player = models.ForeignKey(Player)
    bots = models.ManyToManyField(Robot)
    num_bots = models.IntegerField(default = 1)


class Challenge(models.Model):
    challenger = models.OneToOneField(Team, related_name = 'challenger')
    challengee = models.ForeignKey(Team, related_name='challengee', null = True, blank = True, unique = False)
    num_bots = models.IntegerField(default = 1)
    date = models.DateField(auto_now_add = True)

bots/forms.py
from django import forms
from django.contrib.auth.models import User
from bots.models import Player



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

bots/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth import logout
from bots.models import *
from bots.forms import *
from bots.matchmaking import matchmake, get_matches, challenge
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def index(request):
    context =  {'players' : Player.objects.all().order_by('-user__date_joined')[:5]}
    # shows the 5 most newest players
    return render(request, 'bots/index.html', context)


def show_profile(request, profile_name):
    # try to retrieve info about player
    try:
        player = Player.objects.get(user__username = profile_name)
    except: # no player found
        player = None
        context = {'player': None}

    if player:
        context = {
            'player': player,
            # number of robots the player owns
            'number_of_robots' : len(Robot.objects.filter(owner = player)),
            # players this player is following
            'followees' : player.follows.all(),
            # the 5 most valuable robots the player owns
            'top5_valuable_robots' : Robot.objects.filter(owner=player).order_by('-value')[:5],
            # top5 robots with the most wins
            'top5_winning_robots' : Robot.objects.filter(owner=player).order_by('-wins')[:5],
            # list of player's robots
            'robots' : Robot.objects.filter(owner=player),
            # list of stat names
            'stats' : ['speed', 'dodge', 'armour', 'weapon', 'accuracy'],
            'battleHistory' : Battle.objects.filter(participants = player).order_by('-date')
        }
        #returns information about a player so that their profile can be rendered

    return render(request, 'bots/profile.html', context)


def upgrade(request):
    ''' ajax view used for increasing stats of robots'''
    if request.method == 'GET':
        stat = request.GET.get('stat',"")
        bot_name = request.GET.get('bot_name',"")

        #try to  find robot with given id
        try:
            bot = Robot.objects.get(name = bot_name)

            if(stat == 'speed'):
                bot.owner.scrap -= bot.speed*25
                bot.speed += 1
            elif(stat == 'dodge'):
                bot.owner.scrap -= bot.dodge*25
                bot.dodge+= 1
            elif(stat == 'armour'):
                bot.owner.scrap -= bot.armour*25
                bot.armour+= 1
            elif(stat == 'weapon'):
                bot.owner.scrap -= bot.weapon*25
                bot.weapon+= 1
            elif(stat == 'accuracy'):
                bot.owner.scrap -= bot.accuracy*25
                bot.accuracy+= 1

            bot.save()
            bot.owner.save()
        # returned new rendered table
            response =  render(request, 'bots/bot_table.html', {
                'robot' : bot,
                'stats' : bot.get_stats(),
                'player' : bot.owner,
                'editable': True})
            return response
        except: # invalid robot id
            print('upgrade was called with invalid robot id!!!')
            # assume player has enough scrap, since otherwise they wouldnt have access to button that calls this
            return render(request, 'bots/bot_table.html',{'message': bot_name})



def display_bot(request):
    if request.method == "GET":
        bot_name = request.GET.get('bot_name','')
        # retrieves information about a robot so that it can be displayed

        try:
            bot = Robot.objects.get(name = bot_name)
            if bot.owner.user.username == request.user.username:
                editable = True
            else:
                editable = False
                # boolean flag to indicate if the user will be able to upgrade this robot

            response =  render(request, 'bots/bot_table.html', {
            'robot' : bot,
            'stats' : bot.get_stats(),
            'player' : bot.owner,
            'editable':editable,})
            return response
        except:
            return render(request,'bots/bot_table.html',{})





def validate(request):
    # validates a list of robots to check if they are unique and accessible,
    # if valid it will then begin the matchmaking process and render lists of which can be played
    if request.method == "GET":
        size = int(request.GET.get('size',0))
        name = request.GET.get('name','')
        returner = {}
        bots = []
        valid = True
        bot_names = []

        msg = 'everything works'
        player = Player.objects.get(user__username = name)
        for i in range(size):
            bot_names.append(request.GET.get('b' + str(i),''))


        for i in range(size):
            for j in range(i + 1,size):

                if bot_names[i] == bot_names[j]:
                    valid = False
                    msg = 'duplicate bot found'

        try:
            bots.append(Robot.objects.get(name = bot_names[i]))
        except:
            valid = False
            'bot ' + bot_names[i] + ' not found'


        valid = valid and len(bots) > 0
        if valid:
            # generates 2 lists of games (ones who have challened me, and ones who I am able to challenge) and the newly formed team
            received, sent, t = matchmake(player, bots, size)

            return render(request, 'bots/matchmake.html',{'valid':True, 'team':[i.name for i in t.bots.all()],'received':received,'sent':sent, 'size':size, 'msg':'Team found everything worked'})


        else:
            # the team was invalid so the matchmaking doesn't happen
            bots = Robot.objects.filter(owner = player)
            return render(request,'bots/matchmake.html',{
                'valid':False,
                'robots':bots,
                'player':name,
                'team':bot_names,
                'size':size,
                'msg':msg,
                })


def resetTeam(request):
    #removes a players current team so that it can be updated
    if request.method == 'GET':
        size = int(request.GET.get('size',0))
        name = request.GET.get('name','')
        team = Team.objects.get(player = name, num_bots = size)
        team.delete()
        #deletes old team

        player = Player.objects.get(user__username = name)
        bot_names = []
        bots = Robot.objects.filter(owner = player)
        for i in range(size):
            bot_names.append(request.GET.get('b' + str(i),''))
        # git list of all robots owned by the player so that they are eligable to be added to the team

        return render(request, 'bots/matchmake.html',{'valid':False, 'team':bot_names,'robots':bots,'games':'','size':size, 'msg':'please update your team:'})


def initialize(request):
    # used to retrieve matchmaking info when a page is first loaded
    if request.method == 'GET':
        size = int(request.GET.get('size',0))
        name = request.GET.get('name','')

        player = Player.objects.get(user__username = name)
        if player:

            try:
                t = Team.objects.get(player = player, num_bots = size)
            except:
                t = None

            if t:
                received, sent = get_matches(t, size)
                try:
                    # checks if player has already challenged a different player
                    challenge = Challenge.objects.get(challenger = t, num_bots = size)
                    return render(request, 'bots/matchmake.html',{'valid':True, 'team':[i.name for i in t.bots.all()],'received':received,'sent':sent,'challengee':challenge.challengee, 'size':size, 'msg':'Team found everything worked'})
                except:
                    # else displays list of possible matches
                    return render(request, 'bots/matchmake.html',{'valid':True, 'team':[i.name for i in t.bots.all()],'received':received,'sent':sent, 'size':size, 'msg':'Team found everything worked'})

            else:
                # no current team, so player must make one in order to matchmake
                bots = Robot.objects.filter(owner = player)
                return render(request, 'bots/matchmake.html',{'valid':False,'robots':bots,'size':size,'team':range(size),'msg':'no team found'})

        else:
            # error no player found so returns a message saying that no player was found
            return render(request, 'bots/matchmake.html',{'valid':False, 'size':size,'msg':'player not found: ' + name})


def fight(request):
    # sends a battle request to another player
    if request.method == 'GET':
        name = request.GET.get('name','')
        size = int(request.GET.get('size',''))
        opponent = request.GET.get('opponent','')


        me = Player.objects.get(user__username = name)
        them = Player.objects.get(user__username = opponent)


        my_team = Team.objects.get(player = me, num_bots = size)
        dbug = challenge(me, them,size, my_team.bots.all())

        if(dbug == 0):
            # you have accepted another players challenge and the battle has been completed
            return HttpResponse('Accepted challenge from '+ opponent)
        elif(dbug == 1):
            # you have sent a challenge to another player but they have not yet accepted it
            return HttpResponse('Challenge Sent to '+ opponent + ' they must accept before the match commences')
        else:
            # you have already sent a different player a challenge and cannot send one to another
            return HttpResponse('You Have already challenged ' + opponent +', you may not challenge another player yet')








def validate_name(request):
    # checks to see if the name given to a new robot is
    if request.method == 'GET':
        name = request.GET.get('name','')
        type = request.GET.get('type','')

templates/bots/about.html
{% extends 'bots/base.html' %}
{% load staticfiles %}

{% block title_block %}
	About
{% endblock %}


{% block content_block %}

<p> About SCRAPBOTS: <br>
SCRAPBOTS is a simple battling game which allows players to create robots using Scrap, battle other users' robots
and collect Scrap as a reward and to continuesly improve their robots and to improve their rank in the leaderboards
</p>
<p> Robots: <br>
Users have a choice of creating 3 types of robots: Aerial, Bipedal and Wheeled which all have certain
advantage over the other when first created
</p>

<p> Battles: <br>

	Users can anounce that they are open to battle by activiating the matchmaking button in
	their profile page and have a choice of battling with a team of 1,3 and 5 robots.

</p>


{% endblock %}

templates/bots/base.html
<!DOCTYPE HTML>
{% load bots_template_tags %}
{% load staticfiles %}

<html>
		<head lang="en">
			<meta charset="UTF-8" />
			<!-- Stylesheet -->
			<link rel="stylesheet" type="text/css" href="{%static 'css/base.css' %}">

			<!-- ICON shown beside the title in the browser -->
			<link rel="icon" href="{% static 'images/icon.ico' %} ">

			<!-- START TITLE -->
			<title>
				SCRAPBOTS |
				{% block title_block %}
					PLAY!
				{% endblock %}
			</title>
			<!-- END TITLE -->

		</head>

	<body>
		<!-- Navigation Bar-->
		<div id="nav-bar">

			<!-- navigation links -->
			<a id="logo" href="{% url 'index' %}"> <strong id = "logo"> SCRAPBOTS </strong> </a>
			<a id="nav-link" href="{% url 'bots:leaderboards' %}"> LEADERBOARDS </a>
			<a id="nav-link" href="{% url 'bots:about' %}"> ABOUT </a>
			<!-- END NAVIGATION LINKS -->

			{% if user.is_authenticated %}				
			<div id="dropdown">
			<button id=play> Signed in as {{ user.username }} ▼</button>
				<!--menu-->
				<!-- Is rendered if there is no user logged in -->

				<div id="menu">
				<a id="dropdown-link" href="{% url 'bots:show_profile' user.username %}"> View Profile </a> <br>
				<a id="dropdown-link" href="{% url 'bots:signout' %}"> Sign Out </a>
				</div>

				<!-- END MENU -->

			</div>

			{% else %}

			<!--will make a dropdown button for play and when hovered will display the menu-->

			<div id="dropdown">
			<button id=play> PLAY ▼</button>
				<!--menu-->
				<!-- is rendered when user is logged in -->

				<div id="menu">
				<a id="dropdown-link" href="{% url 'bots:signin' %}"> Sign in </a> <br>
				<a id="dropdown-link" href="{% url 'bots:signup' %}"> Sign Up </a>
				</div>

				<!-- END MENU -->

			</div>

			{% endif %}
		</div>
		<!--END NAVIGATION BAR-->

		<!-- PAGE CONTENT-->
		<div id="content">
			{% block content_block %}

			SCRAPBOTS

			{% endblock %}
		</div>
		<!-- END CONTENT -->

		<!-- SCRIPTS -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
		<script src="{% static 'js/jquery.js' %}"></script>
	</body>
</html>

templates/bots/bot_table.html
{% load bots_template_tags %}

<div>
    <div id = 'display_bot'>

        <!-- If user owns at least one robot -->
        {% if robot %}
            <table>

                <!-- displaying the selected robot's stats -->
                <tr><td>Type</td><td>{{ robot.type }}</td></tr>
                <tr><td>Wins</td><td>{{ robot.wins }}</td></tr>
                <tr><td>Losses</td><td>{{ robot.losses }}</td></tr>
                {% for stat, value in stats.items %}
		        <tr><td>{{ stat }}</td><td>{{ value }}</td>
			        {% if player.scrap|add:0 >= value|mult:25 %}
			        <td>
                        <!-- if user has enough scrap they can upgrade a stat -->
			            {% if editable %}
			        	<button class="stat-increase" data-stat="{{ stat }}" data-botid="{{ robot.name }}">+</button>
			        	{% endif %}
			        </td>
			        {% endif %}

		        </tr>
	            {% endfor %}

            </table>

        <!-- if user doesn't own any robots  -->
        {% else %}
            You don't currently own any Robots!
        {% endif %}
    </div>

</div>

templates/bots/create_bot.html
{% load bots_template_tags %}

<div>

    <h3>Create a New Robot</h3>


    <!-- if user has scrap more than 7 -->
    {% if player.scrap >= 7 %}

    <!-- can create a robot of either type aerial, bipedal or wheeled -->
        <form name = 'CreateBot'>
            Name: <input id = 'new_bot_name' type = 'text' required>
            Type:
            <select>
                <option value = 'aerial'>Aerial</option>
                <option value = 'bipedal'>Bipedal</option>
                <option value = 'wheeled'>Wheeled</option>
            </select>

            <input type="submit" value="Submit">

        </form>

        <div id = 'create_bot_err'></div>

    <!-- if user doesn't have enough scrap -->
    {% else %}

        <strong>You don't have enough Scrap to make a new Robot!</strong>


    {% endif %}

</div>

templates/bots/index.html
{% extends 'bots/base.html' %}
{% load staticfiles %}

{% block title_block %}
Home
{% endblock %}

{% block content_block %}

<div id="section">

<!-- index page will show newest user to have joined the web app -->
<h3 id="profile-header" > Newest Users </a>
<table>
{% for player in players %}
    <tr>
        <td>
            <a id="dropdown-link" href="{% url 'bots:show_profile' player.user.username %}">{{ player.user.username }}</a>
        </td>
        <td>
            <h4 id="profile-sub-header">{{ player.user.date_joined }}</h4>

        </td>
    </tr>
{% endfor %}
</table>

</div>

{% endblock %}

templates/bots/leaderboards.html
{% extends 'bots/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Leaderboards
{% endblock %}

{% block content_block %}

	<!--START ROBOT LEADERBOARD-->
	<div id="section">
		<h3 id="profile-header"> Top Robots </h3>
		<ol>
		{% for bot in top_bots %}				
		<li>
		robot: {{bot}} <br>
		owned by: <a id="dropdown-link" href="{% url 'bots:show_profile' bot.owner %}"> {{bot.owner}} </a>
		</li><br>
		{% endfor %}	
		</ol>
	</div>
	<!--END ROBOT LEADERBOARD-->

	<!--START USER LEADERBOARD-->
	<div id="section">
		<h3 id="profile-header"> Top Users </h3>
		<ol>		
		{% for player in top_users %}				
		<li>
		<a id="dropdown-link" href="{% url 'bots:show_profile' player %}"> {{player}} </a>
		</li><br>	
		{% endfor %}
		</ol>
		
		
	</div>
	<!--END USER LEADERBOARD-->

{% endblock %}

templates/bots/matchmake.html
{% load bots_template_tags %}
{% load static %}

<div id="matchmake-section">

<!-- battle requests received -->
<div id = '{{ size }}v{{ size }}_complete'>
    <h3 id="profile-header">{{ size }}V{{ size }} Battle</h3>
    <div>
        {% if valid %}
            {% for bot in team %}

                <div id = '{{ size }}v{{ size }}_{{ forloop.counter0 }}'>{{ bot }}</div>

            {% endfor %}
               
            <div><button id = '{{ size }}v{{ size }}_find_game'>Refresh Team!</button></div>

        {% else %}
                {% for bot in team %}
                    <select id = "{{ size }}v{{ size }}_{{ forloop.counter0 }}">

                        {% for robot in robots %}

                            <option value = "{{ robot.name }}">{{ robot.name }}</option>

                        {% endfor %}
                    </select>

                {% endfor %}

                    <button id = '{{ size }}v{{ size }}_find_game'>Find Game!</button>

        {% endif %}


    </div>

    <div id="matchmake-sub-section">

    <!-- users open for battle -->
    <div id = 'gameList'>
        {%if valid %}
        <table>
                <th colspan = 3><h4 id="profile-sub-header">Challenges I have received</h3></th>
            {% if received %}
            {% for i in received %}
            <tr>
                <td>{{ i.player.user.username }}</td>

                <td><select id = '{{ size }}_enemy'>
                    {% for bot in i.bots.all %}
                    <option value = '{{ bot.name }}'>{{ bot.name }}</option>
                    {% endfor %}
                </select></td>
                <td><button class = '{{ size }}v{{ size }}_play' value = '{{ i.player.user.username }}'>FIGHT!</button></td>
            </tr>
            {% endfor %}
            <tr><div id = '{{ size }}_enemy_stats'></div></tr>


            {% else %}
            <tr><td>You currently have no battle requests</td></tr>

            {% endif %}

        </table>

    </div>
    </div>




        <div id="matchmake-sub-section">

            {% if challengee %}
                You have already challenged {{ challengee.player.user.username }}, you must either refresh your team or wait for {{ challengee.player.user.username }} to accept your challenge!

            {% else %}
            <table>
                <th colspan = 3><h3 id="profile-sub-header">Players ready to be challenged</h3></th>
                {% for i in sent %}
                <tr>
                    <td>{{ i.player.user.username }}</td>

                    <td><select id = '{{ size }}_enemy'>
                        {% for bot in i.bots.all %}
                        <option value = '{{ bot.name }}'>{{ bot.name }}</option>
                        {% endfor %}
                    </select></td>
                    <td><button class = '{{ size }}v{{ size }}_play' value = '{{ i.player.user.username }}'>FIGHT!</button></td>
                </tr>
                {% endfor %}
                <tr><div id = '{{ size }}_enemy_stats'></div></tr>
                </table>
            {% endif %}
        {% else %}
            <p>Please enter {{ size }} unique bots</p>

        {% endif %}

    </div>



</div>
</div>

templates/bots/signin.html
{% extends 'bots/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Sign in
{% endblock %}


{% block content_block %}

<h1>Login to SCRAPBOTS</h1>
<form id="login_form" method="post" action="{% url 'bots:signin' %}">
{% csrf_token %}
Username: <input type="text" name="username" value="" size="50" />
<br />
Password: <input type="password" name="password" value="" size="50" />
<br />
<input type="submit" value="submit" />
Don't have an account? <a href="{% url 'bots:signup' %}"> Sign Up! </a>
</form>
{% endblock %}

templates/bots/signup.html
{% extends 'bots/base.html' %}
{% load staticfiles %}

{% block title_block %}
Sign Up
{% endblock %}

{% block content_block %}
	<h1>Register for SCRAPBOTS</h1>

	{% if registered %}
		<strong>Thank you for registering!</strong>
		<a href="{% url 'index' %}">Return to the homepage.</a><br />
		{% else %}
			<strong>Please provide the following details</strong><br />
			<form id="user_form" method="post" action="{% url 'bots:signup' %}"
			enctype="multipart/form-data">

			{% csrf_token %}

			<!-- Display each form -->
			{{ user_form.as_p }}

			<!-- Provide a button to click to submit the form. -->
			<input type="submit" name="submit" value="Register" />
			Already have an account? <a href="{% url 'bots:signin' %}"> Sign in! </a>
			</form>
	{% endif %}



{% endblock %}

templates/bots/test.html
<!DOCTYPE html>
{% load bots_template_tags %}
{% load staticfiles %}
<html>
<head>
<title>ScrapBots test</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="{% static 'js/bots/profile-page.js' %}"></script>
</head>
<body>
	<h2>Robots</h2>	
	<div id="bot-table">
		{% get_bot_table bot %}	
	</div>
</body>
</html>

